# This rule is not used by the project dojo-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the core.jutsu.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dojo-operator
    app.kubernetes.io/managed-by: kustomize
  name: dojo-editor-role
rules:
- apiGroups:
  - core.jutsu.com
  resources:
  - dojoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.jutsu.com
  resources:
  - dojoes/status
  verbs:
  - get
